In [1]:
import pandas as pd

In [2]:
news = pd.read_csv(r"D:/new_data/NewsCategorizer.csv")

In [3]:
news.head()

,category,headline,links,short_description,keywords
0,WELLNESS,143 Miles in 35 Days: Lessons Learned,https://www.huffingtonpost.com/entry/running-l...,Resting is part of training. I've confirmed wh...,running-lessons
1,WELLNESS,Talking to Yourself: Crazy or Crazy Helpful?,https://www.huffingtonpost.com/entry/talking-t...,Think of talking to yourself as a tool to coac...,talking-to-yourself-crazy
2,WELLNESS,Crenezumab: Trial Will Gauge Whether Alzheimer...,https://www.huffingtonpost.com/entry/crenezuma...,The clock is ticking for the United States to ...,crenezumab-alzheimers-disease-drug
3,WELLNESS,"Oh, What a Difference She Made",https://www.huffingtonpost.com/entry/meaningfu...,"If you want to be busy, keep trying to be perf...",meaningful-life
4,WELLNESS,Green Superfoods,https://www.huffingtonpost.com/entry/green-sup...,"First, the bad news: Soda bread, corned beef a...",green-superfoods

In [4]:
news.isna().sum()

category                0
headline                0
links                   0
short_description       0
keywords             2668
dtype: int64

In [5]:
news.dropna(inplace=True)

In [6]:
news

,category,headline,links,short_description,keywords
0,WELLNESS,143 Miles in 35 Days: Lessons Learned,https://www.huffingtonpost.com/entry/running-l...,Resting is part of training. I've confirmed wh...,running-lessons
1,WELLNESS,Talking to Yourself: Crazy or Crazy Helpful?,https://www.huffingtonpost.com/entry/talking-t...,Think of talking to yourself as a tool to coac...,talking-to-yourself-crazy
2,WELLNESS,Crenezumab: Trial Will Gauge Whether Alzheimer...,https://www.huffingtonpost.com/entry/crenezuma...,The clock is ticking for the United States to ...,crenezumab-alzheimers-disease-drug
3,WELLNESS,"Oh, What a Difference She Made",https://www.huffingtonpost.com/entry/meaningfu...,"If you want to be busy, keep trying to be perf...",meaningful-life
4,WELLNESS,Green Superfoods,https://www.huffingtonpost.com/entry/green-sup...,"First, the bad news: Soda bread, corned beef a...",green-superfoods
...,...,...,...,...,...
49993,SPORTS,Norovirus Outbreak At Winter Olympics Prompts ...,https://www.huffingtonpost.com/entry/norovirus...,Troops will replace hundreds of civilian secur...,norovirus-outbreak-at-winter-olympics-prompts-...
49995,SPORTS,This Baseball Team Learned There's A Wrong Way...,https://www.huffingtonpost.com/entry/san-jose-...,Many fans were pissed after seeing the minor l...,san-jose-giants-japanese-heritage-night
49996,SPORTS,Some Young Spurs Fan Dabbed 38 Times In A Sing...,https://www.huffingtonpost.com/entry/dab-kid-s...,"Never change, young man. Never change.",dab-kid-san-antonio-spurs
49997,SPORTS,Rasheed Wallace Ejected From Knicks-Suns Game ...,https://www.huffingtonpost.com/entry/rasheed-w...,Wallace was hit with a first technical for a h...,rasheed-wallace-ejected-knicks-suns-ball-dont-lie
49999,SPORTS,"Simone Biles Isn't The Next Anyone, She's 'The...",https://www.huffingtonpost.com/entry/the-first...,The gymnast is in a league of her own.,the-first-simone-biles

In [7]:
news.isna().sum()

category             0
headline             0
links                0
short_description    0
keywords             0
dtype: int64

In [8]:
import pandas as pd
import re
import string
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

In [9]:
nltk.download('punkt') 
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to D:\anaconda\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to D:\anaconda\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to D:\anaconda\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to D:\anaconda\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [10]:
stop_words = set(stopwords.words('english'))
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

In [11]:
def remove_noise(text):
    text = re.sub(r'@\w+', '', text)                   # remove mentions (@user)
    text = re.sub(r'#\w+', '', text)                   # remove hashtags (#word)
    text = re.sub(r'http\S+|www\S+', '', text)         # remove links
    text = re.sub(r'\d+', '', text)                    # remove numbers
    text = re.sub(r'[^\x00-\x7F\u0600-\u06FF]', '', text)  # remove emojis & special chars
    return text

In [12]:
def to_lowercase(text):
    return text.lower()

In [13]:
def remove_punctuation(text):
    return text.translate(str.maketrans('', '', string.punctuation))

In [14]:
def tokenize_text(text):
    return word_tokenize(text)

In [15]:
def remove_stopwords(tokens):
    return [t for t in tokens if t not in stop_words]

In [16]:
def apply_stemming(tokens):
    return [stemmer.stem(t) for t in tokens]

In [17]:
def apply_lemmatization(tokens):
    return [lemmatizer.lemmatize(t) for t in tokens]

In [18]:
def preprocess_text(text):
    if not isinstance(text, str):
        return ""

    text = remove_noise(text)
    text = to_lowercase(text)
    text = remove_punctuation(text)
    tokens = tokenize_text(text)
    tokens = remove_stopwords(tokens)
    tokens = apply_stemming(tokens)
    tokens = apply_lemmatization(tokens)

    return " ".join(tokens)

In [19]:
news['clean_short_description'] = news['short_description'].apply(preprocess_text)

In [20]:
news['clean_headline'] = news['headline'].apply(preprocess_text)

In [21]:
news.to_csv(
    r"D:\cleaned_dataset.csv",
    index=False,
    encoding="utf-8-sig"
           )
print(" Cleaned dataset saved as 'cleaned_dataset.csv'")

 Cleaned dataset saved as 'cleaned_dataset.csv'

In [22]:
print("\n Sample before and after preprocessing:\n")
for i in range(5):
    print("Original:", news.iloc[i]['short_description'])
    print("Cleaned :", news.iloc[i]['clean_short_description'])
    print("-" * 100)

 Sample before and after preprocessing:

Original: Resting is part of training. I've confirmed what I sort of already knew: I'm not built for running streaks. I'm built for hard workouts three to five days a week with lots of cross training, physical therapy and foam rolling. But I've also confirmed that I'm stubborn with myself.
Cleaned : rest part train ive confirm sort alreadi knew im built run streak im built hard workout three five day week lot cross train physic therapi foam roll ive also confirm im stubborn
----------------------------------------------------------------------------------------------------
Original: Think of talking to yourself as a tool to coach yourself through a challenge, or to narrate your own experiences to yourself. In any case, treat yourself with respect and you just may find you enjoy your own company.
Cleaned : think talk tool coach challeng narrat experi case treat respect may find enjoy compani
----------------------------------------------------------------------------------------------------
Original: The clock is ticking for the United States to find a cure. The team is working on the study with Dr. Francisco Lopera of
Cleaned : clock tick unit state find cure team work studi dr francisco lopera
----------------------------------------------------------------------------------------------------
Original: If you want to be busy, keep trying to be perfect.  If you want to be happy, focus on making a difference.
Cleaned : want busi keep tri perfect want happi focu make differ
----------------------------------------------------------------------------------------------------
Original: First, the bad news: Soda bread, corned beef and beer do not a highly nutritious meal make. But as luck (of the Irish!) would
Cleaned : first bad news soda bread corn beef beer highli nutriti meal make luck irish would
----------------------------------------------------------------------------------------------------

In [23]:
print("\n Sample before and after preprocessing:\n")
for i in range(5):
    print("Original:", news.iloc[i]['headline'])
    print("Cleaned :", news.iloc[i]['clean_headline'])
    print("-" * 100)

 Sample before and after preprocessing:

Original: 143 Miles in 35 Days: Lessons Learned
Cleaned : mile day lesson learn
----------------------------------------------------------------------------------------------------
Original: Talking to Yourself: Crazy or Crazy Helpful?
Cleaned : talk crazi crazi help
----------------------------------------------------------------------------------------------------
Original: Crenezumab: Trial Will Gauge Whether Alzheimer's Drug Can Prevent Or Slow The Disease
Cleaned : crenezumab trial gaug whether alzheim drug prevent slow diseas
----------------------------------------------------------------------------------------------------
Original: Oh, What a Difference She Made
Cleaned : oh differ made
----------------------------------------------------------------------------------------------------
Original: Green Superfoods
Cleaned : green superfood
----------------------------------------------------------------------------------------------------

In [24]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

In [25]:
# دمج العنوان والوصف في عمود جديد
news['text'] = news['headline'] + " " + news['short_description']

# بعد كده 'text' ده هيكون X
X = news['text']

# و Y هو العمود اللي عايز تتنبأ بيه
y = news['category']

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer  #

tfidf = TfidfVectorizer(
    stop_words='english',
    max_features=15000                      #اقصي عدد كلمات بيستخدمها الموديل عشان التدريب الكلمات الغير شائعة
)

X_tfidf = tfidf.fit_transform(X)

X_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 717084 stored elements and shape (47332, 15000)>

In [27]:
#تقسيم الداتا الي # train test split (80% train - 20% test)
X_train, X_test, y_train, y_test = train_test_split(
    X_tfidf, y, test_size=0.2, random_state=42
)
print('Training Data :', X_train.shape)
print('Testing Data : ', X_test.shape)
print('testing Data :', y_train.shape)
print('testing Data : ', y_test.shape)

Training Data : (37865, 15000)
Testing Data :  (9467, 15000)
testing Data : (37865,)
testing Data :  (9467,)

In [28]:
model = LogisticRegression(
    max_iter=1000,
    n_jobs=-1
)

model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, n_jobs=-1)

In [29]:
y_pred = model.predict(X_test)

y_pred

array(['ENTERTAINMENT', 'ENTERTAINMENT', 'BUSINESS', ..., 'ENTERTAINMENT',
       'BUSINESS', 'WORLD NEWS'], dtype=object)

In [30]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Precision
precision = precision_score(y_test, y_pred, average='weighted')
print("Precision:", precision)

# Recall
recall = recall_score(y_test, y_pred, average='weighted')
print("Recall:", recall)

# F1-score
f1 = f1_score(y_test, y_pred, average='weighted')
print("F1-score:", f1)

# Report كامل
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

Accuracy: 0.824020280976022
Precision: 0.8248180868073248
Recall: 0.824020280976022
F1-score: 0.8241499465395986

Classification Report:

                precision    recall  f1-score   support

      BUSINESS       0.78      0.79      0.79       908
 ENTERTAINMENT       0.79      0.82      0.81       923
  FOOD & DRINK       0.86      0.86      0.86       987
     PARENTING       0.81      0.79      0.80       900
      POLITICS       0.81      0.76      0.78       955
        SPORTS       0.90      0.92      0.91       968
STYLE & BEAUTY       0.89      0.85      0.87       903
        TRAVEL       0.83      0.81      0.82       958
      WELLNESS       0.74      0.80      0.77       969
    WORLD NEWS       0.83      0.83      0.83       996

      accuracy                           0.82      9467
     macro avg       0.82      0.82      0.82      9467
  weighted avg       0.82      0.82      0.82      9467

In [31]:
import joblib

joblib.dump(model, 'logistic_model.pkl')
print("Successfully")

Successfully

In [39]:
# validation data
X_test_sample = news[['headline', 'short_description', 'category']] \
                    .sample(n=5000, random_state=42)

X_test_text = X_test_sample['headline'] + " " + X_test_sample['short_description']
y_true = X_test_sample['category']

X_test_vec = tfidf.transform(X_test_text)

y_pred = model.predict(X_test_vec)

accuracy = accuracy_score(y_true, y_pred)
print("Accuracy:", accuracy * 100, "%")

Accuracy: 82.8 %

In [33]:
import os
os.getcwd()

'C:\\Users\\Access\\anaconda_projects\\1d300c61-4048-4171-920c-36ee9fadf19e'

In [34]:
# Example of testing the model with a new text
new_text = [
          ("Stock markets rally after inflation slowdown",
          "Global stock markets rose sharply after new data showed a slowdown in inflation rates.")]
external_df = pd.DataFrame(
    new_text,
    columns=["headline", "short_description"]
)

external_df
X_external = external_df['headline'] + " " + external_df['short_description']
X_external

0    Stock markets rally after inflation slowdown G...
dtype: object

In [35]:
import re

def preprocess_single_text(text_input):
    r = re.sub('[^a-zA-Z]', ' ', text_input)
    r = r.lower()
    r = r.split()
    r = ' '.join(r)
    return r
X_external_processed = X_external.apply(preprocess_single_text)

print(f"Original text: {X_external}")
print(f"Preprocessed text: {X_external_processed}")

# Transform the preprocessed text using the trained CountVectorizer
X_new_cv = tfidf.transform(X_external_processed)

# Make a prediction using the trained Logistic Regression model
new_prediction = model.predict(X_new_cv)

print(f"Predicted sentiment: {new_prediction}")

Original text: 0    Stock markets rally after inflation slowdown G...
dtype: object
Preprocessed text: 0    stock markets rally after inflation slowdown g...
dtype: object
Predicted sentiment: ['BUSINESS']

In [36]:
new_text = [
    ("Stock markets rally after inflation slowdown",
     "Global stock markets rose sharply after new data showed a slowdown in inflation rates."),

    ("New vaccine shows promising trial results",
     "Clinical trials reveal high effectiveness for a newly developed vaccine."),

    ("Last-minute goal secures championship victory",
     "A dramatic goal in the final seconds sealed the championship title."),

    ("Tech companies report strong quarterly earnings",
     "Major technology firms exceeded expectations in their latest financial reports."),

    ("Cybersecurity threats increase globally",
     "Experts warn of a rise in sophisticated cyber attacks worldwide."),

    ("Government announces new economic reform plan",
     "Officials unveiled a comprehensive plan aimed at boosting economic growth."),

    ("New smartphone release features advanced camera",
     "The latest smartphone model includes significant upgrades in camera technology."),

    ("WHO warns of rising global health risks",
     "The World Health Organization issued a warning about increasing health threats worldwide."),

    ("Streaming platform releases popular new series",
     "The series quickly gained popularity among global audiences."),

    ("Quantum computing reaches new milestone",
     "Researchers successfully demonstrated a more stable quantum computing system.")
]
import pandas as pd

external_df = pd.DataFrame(
    new_text,
    columns=["headline", "short_description"]
)

external_df

,headline,short_description
0,Stock markets rally after inflation slowdown,Global stock markets rose sharply after new da...
1,New vaccine shows promising trial results,Clinical trials reveal high effectiveness for ...
2,Last-minute goal secures championship victory,A dramatic goal in the final seconds sealed th...
3,Tech companies report strong quarterly earnings,Major technology firms exceeded expectations i...
4,Cybersecurity threats increase globally,Experts warn of a rise in sophisticated cyber ...
5,Government announces new economic reform plan,Officials unveiled a comprehensive plan aimed ...
6,New smartphone release features advanced camera,The latest smartphone model includes significa...
7,WHO warns of rising global health risks,The World Health Organization issued a warning...
8,Streaming platform releases popular new series,The series quickly gained popularity among glo...
9,Quantum computing reaches new milestone,Researchers successfully demonstrated a more s...

In [37]:
X_external = external_df['headline'] + " " + external_df['short_description']
X_external

0    Stock markets rally after inflation slowdown G...
1    New vaccine shows promising trial results Clin...
2    Last-minute goal secures championship victory ...
3    Tech companies report strong quarterly earning...
4    Cybersecurity threats increase globally Expert...
5    Government announces new economic reform plan ...
6    New smartphone release features advanced camer...
7    WHO warns of rising global health risks The Wo...
8    Streaming platform releases popular new series...
9    Quantum computing reaches new milestone Resear...
dtype: object

In [38]:
X_external_processed = X_external.apply(preprocess_single_text)
X_new_cv = tfidf.transform(X_external_processed)
y_pred = model.predict(X_new_cv)
print(f"Predicted category: {y_pred}")
#y_pred

Predicted category: ['BUSINESS' 'WELLNESS' 'SPORTS' 'BUSINESS' 'WORLD NEWS' 'BUSINESS'
 'BUSINESS' 'WELLNESS' 'ENTERTAINMENT' 'WELLNESS']